name: CI Static Code Analysis

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v4.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_URL: ${{vars.SONAR_HOST_URL}}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=MLService
            -Dsonar.python.coverage.reportPaths=coverage.xml

      - name: Quality Gate
        id: sonarqube
        uses: sonarsource/sonarqube-quality-gate-action@v2.0.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_URL: ${{vars.SONAR_HOST_URL}}
        with:
          host-url: $SONAR_URL
          project-key: MLService
          auth: $SONAR_TOKEN
