name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt
        pip install pytest-cov
    
    - name: Download ZIP
      run: |
        curl -o file.zip https://mediaops-public.s3.us-east-1.amazonaws.com/at-bootcamp/testsimages.zip

    - name: Unzip ZIP
      run: |
        mkdir -p uploads/Filexample/
        unzip -j file.zip "testsimages/*" -d uploads/Filexample/

    - name: Verify folder content
      run: |
        ls -la uploads/Filexample/

    - name: Run unit tests and check code coverage
      run: |
        python3 -m pytest --cov=models/Recognizer --cov-report=term tests/models_tests/ 
        python3 -m pytest --cov=routes --cov-report=term tests/routes_tests/
        python3 -m pytest --cov=utils --cov-report=term tests/utils_tests/ 
